### PR TITLE
Update GPU images to work properly on Nvidia A100 nodes

### PR DESCRIPTION
**Pull request by super-cooper**
Sets the `pci=realloc=off` kernel parameter in the grub config

### CODE REVIEW

**Comment by super-cooper** [comment]
[update ubuntu-gpu images with kernel commandline flag for a100 nodes](https://trello.com/c/CZB2jURq/2907-update-ubuntu-gpu-images-with-kernel-commandline-flag-for-a100-nodes)

**Review by msherman64 — APPROVED** [review]
You might be able to set the cmdline more cleanly by using the `DIB_BOOTLOADER_DEFAULT_CMDLINE` variable from the bootloader element.
https://docs.openstack.org/diskimage-builder/latest/elements/bootloader/README.html

Disabling Noveau is also for a GPU related fix?

Overall LGTM, just please ensure that the commits are squashed, and commit message details the purpose of each change.

**Comment by msherman64** [comment]
You can also blacklist modules using the `DIB_MODPROBE_BLACKLIST` env, from https://docs.openstack.org/diskimage-builder/latest/elements/modprobe/README.html

**Comment by super-cooper** [comment]
> Disabling Noveau is also for a GPU related fix?

We already disabled Nouveau, but I encountered errors while building because it attempted to disable Nouveu without it being installed. I just added the if-statement to ensure it's actually installed before disabling it.

**Comment by super-cooper** [comment]
I attempted to make the changes through the environment variables you mentioned, but it seems to be causing issues for the nvidia installer for some reason. I think we can revisit this once the changes for Ubuntu22 are in, because it installs CUDA in a more sane way.

**Pull request merged**
